
[client]
showSidebarNavigation = false
# Define o modo da barra de ferramentas (minimal remove o menu desnecessário)
toolbarMode = "minimal"                                                                          
